### ISSUE TITLE
upgrade to font-awesome-5

### ISSUE THREAD

**Issue by logicminds** [wmira/react-icons-kit#16]

**Comment by logicminds** [comment]
I tried to do this myself

```
npm i --save @fortawesome/fontawesome
npm install
cd scripts
node ./scripts/extract-fontawesome.js
```

But this resulted in error

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'charCodeAt' of undefined
    at /Users/user1/react-icons-kit/node_modules/svgfont2js/index.js:56:40
    at Parser.<anonymous> (/Users/user1/react-icons-kit/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onclosetag (/Users/user1/react-icons-kit/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/Users/user1/react-icons-kit/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/user1/react-icons-kit/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/user1/react-icons-kit/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Users/user1/react-icons-kit/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Users/user1/react-icons-kit/node_modules/xml2js/lib/parser.js:322:31)
```

Not sure where to go from here.

**Comment by wmira** [comment]
@logicminds FontAwesome 5 already has an react library and outputs svg. Im closing this now. Please visit:
https://github.com/FortAwesome/react-fontawesome
